### ISSUE TITLE
server side (nodejs) support

### ISSUE THREAD

**Issue by futurist** [franciscop/cookies.js#11]
When browser using this lib, then send data to server(nodejs), the cookies in server side is url-encoded, users can decode it, but the best is to also install this lib in server side, use same API to read cookie values.

It's best to make options to set env when not in browsers, to replace `window` and `document` object, or a way to make it run in nodejs.

**Comment by franciscop** [comment]
I would either have to create a server-side script for each of the languages or risk visitors think this library is only/mainly for Node.js.

I think a simple urldecode does not warrant installing a whole cookies library. Also each back-end handles cookies in a different way while there's a consistent front-end API. So this is not something that will be implemented.
