### ISSUE TITLE
Altering user experience with cookies

### ISSUE THREAD

**Issue by vilav** [franciscop/cookies.js#12]
Hi Francisco

I'm new to JS hence the noob questions:

 - Is there a way to have a periodic setting / resetting of cookies such that every other week, based on how often the user visits a website, they're shown or not show a specific DIV

For example: if a user has been visiting a website atleast once a day for 1 week, then you can show them a newsletter subscription form. If they haven't fulfilled the condition, then they don't see it.

This is one use case, but you can imagine the creation of a more modular system where DIVs can have a HTML data-* attribute (ex: data-cookie=1w / data-cookie=1m) applied such that they auto-show / hide based on a certain defined cookie setting?

Is this sort of thing possible to approach with cookies.js?

**Comment by franciscop** [comment]
Hi, thanks for the question. Yes, it is possible, cookies.js is simply a cookie CRUD tool. However your question is more high level and you seem to be asking for advice about Javascript. The issues tab in Github are reserved for issues about the library or talking about the library itself, not as a general support forum for any question that involves this library.

[Javascript in Reddit](https://www.reddit.com/r/javascript/) might be of help. If you have any more specific issue after trying some solutions, [https://stackoverflow.com/](StackOverflow) might also be useful.
