### ISSUE TITLE
Feature: Translate to ES2015

### ISSUE THREAD

**Issue by marcobiedermann** [franciscop/cookies.js#2]
How about translating to ES2015 and using some features of the new syntax?
If you like, I could help you with that :)

**Comment by franciscop** [comment]
Hi @marcobiedermann , I think the browser support is not that great yet and for such a small library it'd add more overhead than benefit

**Comment by marcobiedermann** [comment]
@franciscop Thank you for your quick reply, but I have a different point of view on it.

> the browser support is not that great yet

That is not true, modern browsers nearly support every feature, for older browsers, I suggest using a transpiler like babel to deliver an ES5 solution.

> for such a small library it'd add more overhead than benefit

This is not all true. I use ES2015 in all my project in combination with other libraries. It would save me some bytes because the syntax is way more cleaner.

Also ES2015 will be the the standard in the future, so my opinion is to use it early and shim older browsers.

I would go for something like this:

```
source/cookies.js (ES6)
dist/cookies.js (ES5)
dist/cookies.min.js (ES5)
```

This would serve everyones needs

**Comment by franciscop** [comment]
The project is 673 bytes when gzipped; you can deliver the js mainly in two ways:

1. You deliver it through a CDN, so the round trip is orders of magnitude larger than the time it takes to send those 673 bytes over (let's say) 500 bytes.
2. You include it in your project and gzip it. Then, either the point 1. is relevant (round trip for js is much larger) or the rest of your javascript is so large it doesn't matter making this a tiny bit smaller.

So the benefit is insignificant about the size.

Now about a library that should be simple and do only one thing (such as this), I find having several points of entry and then having to add the explanation about each of them would add unnecessary noise to the developer who just wants to use the library.

PS, I would totally agree that ES6 would help some libraries, say [Umbrella JS](https://github.com/umbrellajs/umbrella) (another project of mine). But I think for cookies.js it doesn't really make sense.

**Comment by marcobiedermann** [comment]
@franciscop

Alright, thanks for your detailed explaination
