### ISSUE TITLE
Set cookie for all pages/domains except one?

### ISSUE THREAD

**Issue by felixdorner** [franciscop/cookies.js#9]
Hey great little script! However, I am looking for a possibility to set a cookie for all pages except for one? Is this possible and how would I approach this?

**Comment by franciscop** [comment]
Could you explain further, please? What do you mean by *all pages*? (all subdomains, all uris, all domains?)

**Comment by felixdorner** [comment]
Sorry, I try to clarify it. 

I have a WordPress site with pages:

mysite.com
mysite.com/about
mysite.com/work
mysite.com/contact
...

I want to set a cookie when a visitor visits any of these pages except for one:

mysite.com/contact

It this possible with your domain option?

**Comment by TomIsion** [comment]
whether @felixdorner  means (all subdomains, all urls, all domains), I think there just one solution.

**formulate your rule, then limit in the cookie value** like this:

`test=1&expect_path=/about`

**Comment by franciscop** [comment]
I think it's not possible because of the limits of the cookies themselves; cookies.js is just a cleaner API for interacting with cookies. You can set them for specific paths like:

```js
cookies({ token: '42' }, { path: '/' });
```

However there is not an option to exclude a specific path and [this is the closest I could find (but not the same)](http://security.stackexchange.com/q/12439/9161). If it's about reading it, maybe you could do:

```js
var token;
if (window.location.pathname.match(/^\/about/)) {
  token = cookies('token');
}
```

**Comment by felixdorner** [comment]
I thought also about wrapping it in an If statement and checking paths with JS. I will try this out. Thanks guys!

**Comment by franciscop** [comment]
@Tom cookies.js automatically encodes it. You could even do:

```js
cookies({
  token: {
    value: 42,
    exclude: '/contact'
  }
});
```

Then read it:

```js
var token = cookies('token');
var value = token.value;
var exclude = token.exclude;
```

**Comment by felixdorner** [comment]
Hey, isn't this exactly what I wanted to achieve? Creating a cookie which excludes '/contact'?

**Comment by franciscop** [comment]
It doesn't *exclude* it, it just stores the value and then you have to add the same logic as I showed before with the `if()` to exclude it. Options are the second parameter (where a non-existing exclude would go), this is just a *complex* first parameter where I'm storing metadata but it's not functional. What you want would be:

```js
// NOT VALID:
cookies({ token: 42 }, { exclude: '/contact' });
```

But *exclude* is not an existing option, so I was just storing it as metadata for the example.

**Comment by felixdorner** [comment]
I see... Thanks for clarifying.
